language: python

python: 3.5

install:
  - pip install flask
  - npm install -g qunit

 notifications:
    slack: csc400a-s18:DR0cXd2Zsp7iuPZmEElgs9Cp

script:
  - python -m unittest -v test/*.py
  - qunit