language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - npm install -g qunit

before_script:
  - python BackendServer.py &
  - ./BrowserStack --key KzeJ27iophC6F8Lonvhi &

script:
  - python -m unittest -v test/*Test.py
  - qunit
  - python -m unittest -v test/frontend/*Test.py

notifications:
  slack: csc400a-s18:DR0cXd2Zsp7iuPZmEElgs9Cp