language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - npm install -g qunit

before_script:
  - python BackendServer.py &

script:
  - python -m unittest -v test/*Test.py
  - qunit
  - python -m unittest -v test/frontend/*Test.py

notifications:
  slack: csc400a-s18:DR0cXd2Zsp7iuPZmEElgs9Cp

addons:
  browserstack:
    username: "michaelmiddleton2"
    access_key:
      secure: "qyvj++2lLwP2EgmRPf1NunAQho1f5qf2y83YT/Tt3qBSlY0dpxaxWsu2062DiHtk1Uvt7w2owIimovReS7i2bOa2ClXMPATTxy/R9R25UER74M3KypE+r5SjOHJoPrTK5sLjgZUK3WYjzY+oCZXadO+tvuuJ7cY65JRaMI3Au7iyGPvCfKiPBrqJw7hVpX77332l5O54NfAnQl/bGneB+cFvkj2vBnuwvTNbD945nDXBSFXCxt5rYl4Quk1ysi8K88mjJx97Le9SxJM5+WjGtN4VWMLupwfbnus9pBo0gu8yWwif6eosBsEGisYi7HoopCQbAIBm9a6a1/B5BL45KiJbRBlwUhuAIbX4uMzas2N1j54OaSQzh76Wk+h9ld8Tq1f4HNBSqLgCEq5N/1zkiaC5Uttrp5UY0m4Vvg6JtlWgYKhgwHkl40HGscgRmxLC+NukXOOqMn7MYH1NbRcEMbXZ0Z86rViHy+OXgKGfUnZiP0MFw6AyDdLQxKCxgYkGfsd+dcxRBCr9o0YYcsVgDJy0kBHTgajVXZ1CI4h7q5DnjpmIWABwGmBxxSL2QmYerJZUF7gRGtLTRa95mMo96bFdWhCkBJma4ee9lqkE+TBwa46IqhXoqsBYtdtJNLn+WBQ4jUyWVKHG73tPj9DeIzS8kH76vbpE0JuJ/1oIw8U="