language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - npm install -g node-qunit-phantomjs vis

before_script:
  - python BuildMachineSetup.py
  - python BackendServer.py &
  - ./BrowserStackLinux --key $BROWSERSTACK_ACCESS_KEY &
  - ./code-coverage.sh

script:
  - coverage run --omit **/python3.6/**/* -m unittest -v test/*Test.py
  - node-qunit-phantomjs test/junittestharness.html
  - coverage run -a --omit **/python3.6/**/* -m unittest -v test/frontend/*Test.py
  - coverage report --omit *Test.py

after_script:
  - coverage xml --omit *Test.py
  - ./coverage-app after-build -t coverage.py -r $CC_TEST_REPORTER

notifications:
  slack: csc400a-s18:DR0cXd2Zsp7iuPZmEElgs9Cp